# Generated by Django 6.0.5 on 2026-05-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="is_active",
        ),
    ]
